EventIdea.create([
  { name: 'Do Yoga' },
  { name: 'Dress Up for Fun' },
  { name: 'Contribute to a Charitable Group' },
  { name: 'Take a Trip to the Countryside' },
  { name: 'Talk About Sports' },
  { name: 'Meet Someone New' },
  { name: 'Go to a Concert' },
  { name: 'Play Baseball or Softball' },
  { name: 'Plan a Vacation or Trip' },
  { name: 'Buy Something Nice for Myself' },
  { name: 'Make Art (Painting, Sculpture, Drawing, etc.)' },
  { name: 'Read Sacred or Inspirational Works' },
  { name: 'Play Golf' },
  { name: 'Redecorate My Home' },
  { name: 'Go to a Sports Event' },
  { name: 'Do a DIY Project' },
  { name: 'Read a Book' },
  { name: 'Go to a Bar or Club with Friends' },
  { name: 'Attend a Lecture or Speaker Event' },
  { name: 'Go for a Scenic Drive' },
  { name: 'Get Fresh Air' },
  { name: 'Write a Song' },
  { name: 'Meditate' },
  { name: 'Share a Meal with a Friend or Family Member' },
  { name: 'Restore or Fix Up Furniture' },
  { name: 'Watch TV or Movies' },
  { name: 'Go Camping' },
  { name: 'Work on Cars, Bikes, or Motorcycles' },
  { name: 'Think About Good Things in the Future' },
  { name: 'Play Cards' },
  { name: 'Complete a Challenging Task' },
  { name: 'Watch a Comedy Show or Movie' },
  { name: 'Solve a Puzzle or Crossword' },
  { name: 'Take a Relaxing Shower' },
  { name: 'Do Woodworking or Carpentry' },
  { name: 'Write Stories, Poetry, or Plays' },
  { name: 'Spend Time with Animals' },
  { name: 'Go Exploring on a Hike' },
  { name: 'Have an Open Conversation' },
  { name: 'Sing with Others' },
  { name: 'Go to a Party' },
  { name: 'Join a Social or Civic Group' },
  { name: 'Speak a Foreign Language' },
  { name: 'Play a Musical Instrument' },
  { name: 'Make Snacks' },
  { name: 'Go Skiing' },
  { name: 'Brush or Style My Hair' },
  { name: 'Act in a Play or Performance' },
  { name: 'Take a Nap' },
  { name: 'Be with Friends' },
  { name: 'Make Crafts or Preserves' },
  { name: 'Solve a Personal Challenge' },
  { name: 'Take a Bath' },
  { name: 'Make Food or Crafts to Give Away' },
  { name: 'Play Pool or Billiards' },
  { name: 'Play Chess or Checkers' },
  { name: 'Do Pottery, Jewelry, or Other Crafts' },
  { name: 'Do My Hair or Makeup' },
  { name: 'Design or Sketch Ideas' },
  { name: 'Visit Someone in Need' },
  { name: 'Go Bowling' },
  { name: 'Watch Wildlife' },
  { name: 'Garden or Work in the Yard' },
  { name: 'Wear New Clothes' },
  { name: 'Dance' },
  { name: 'Sit in the Sun' },
  { name: 'Relax and Think' },
  { name: 'Go to a Fair, Carnival, or Zoo' },
  { name: 'Talk About Philosophy or Ideas' },
  { name: 'Plan or Organize Something Fun' },
  { name: 'Listen to the Sounds of Nature' },
  { name: 'Go on a Date' },
  { name: 'Have a Lively Conversation' },
  { name: 'Listen to Music' },
  { name: 'Have Friends Over' },
  { name: 'Play in a Sports Competition' },
  { name: 'Introduce Friends to Each Other' },
  { name: 'Give Someone a Gift' },
  { name: 'Get a Massage' },
  { name: 'Watch the Sky or Clouds' },
  { name: 'Work on Improving My Health' },
  { name: 'Explore Downtown' },
  { name: 'Hike' },
  { name: 'Visit a Museum or Exhibit' },
  { name: 'Write Articles or Journals' },
  { name: 'Do a Job Well' },
  { name: 'Go Fishing' },
  { name: 'Go to a Health Club or Spa' },
  { name: 'Learn Something New' },
  { name: 'Compliment Someone' },
  { name: 'Think About People I Care About' },
  { name: 'Spend Time with Parents' },
  { name: 'Ride a Horse' },
  { name: 'Talk on the Phone' },
  { name: 'Daydream' },
  { name: 'Kick Leaves or Pebbles' },
  { name: 'Play Lawn Games' },
  { name: 'Attend a Reunion or Gathering' },
  { name: 'Watch Birds' },
  { name: 'Cook a Meal' },
  { name: 'Do Small Projects Around the House' },
  { name: 'Be at a Family Gathering' },
  { name: 'Host a Get-Together' },
  { name: 'Go to a Restaurant' },
  { name: 'Use Cologne, Perfume, or Aftershave' },
  { name: 'Reminisce with Friends' },
  { name: 'Enjoy a Peaceful Morning' },
  { name: 'Enjoy Peace and Quiet' },
  { name: 'Do a Science Project or Experiment' },
  { name: 'Write in a Journal' },
  { name: 'Play Football, Soccer, or Hockey' },
  { name: 'Say a Prayer' },
  { name: 'Help Someone' },
  { name: 'Talk with Classmates or Coworkers' },
  { name: 'Relax' },
  { name: 'Offer Advice or Support' },
  { name: 'Play Board Games' },
  { name: 'Read the Newspaper or Magazines' },
  { name: 'Play Ping-Pong' },
  { name: 'Swim' },
  { name: 'Go for a Jog or Exercise' },
  { name: 'Walk Barefoot' },
  { name: 'Play Frisbee or Catch' },
  { name: 'Do Housework or Clean' },
  { name: 'Be with a Roommate' },
  { name: 'Visit a Barber or Salon' },
  { name: 'Have House Guests' },
  { name: 'Be with Someone I Love' },
  { name: 'Read Comics or Cartoons' },
  { name: 'Sleep In' },
  { name: 'Start a New Project' },
  { name: 'Finish a Project' },
  { name: 'Go to the Library' },
  { name: 'Prepare a Special Dish' },
  { name: 'People Watch' },
  { name: 'Build or Watch a Fire' },
  { name: 'Repair or Fix Something' },
  { name: 'Work with Others as a Team' },
  { name: 'Ride a Bicycle' },
  { name: 'Smile at People' },
  { name: 'Play in Nature (Sand, Stream, Grass, etc.)' },
  { name: 'Be with My Partner' },
  { name: 'Go on a Nature Walk' },
  { name: 'Express Affection' },
  { name: 'Care for Houseplants' },
  { name: 'Have Coffee or Tea with Friends' },
  { name: 'Take a Walk' },
  { name: 'Collect Things' },
  { name: 'Play Squash or Handball' },
  { name: 'Sew or Knit' },
  { name: 'Remember Loved Ones' },
  { name: 'Spend Time with Children' },
  { name: 'Enjoy a Snack' },
  { name: 'Stay Up Late for Fun' },
  { name: 'Go to a Garage Sale or Auction' },
  { name: 'Think About Interesting Questions' },
  { name: 'Do Volunteer Work' },
  { name: 'Listen to a Good Sermon or Meditation Teaching' },
  { name: 'Make a New Friend' },
  { name: 'Talk About My Interests' },
  { name: 'Travel with a Group' },
  { name: 'See Old Friends' },
  { name: 'Teach Someone' },
  { name: 'Use My Strength' },
  { name: 'Travel Somewhere New' },
  { name: 'Go to a Work or School Party' },
  { name: 'Attend a Concert or Show' },
  { name: 'Play with Pets' },
  { name: 'Go to a Play' },
  { name: 'Look at the Stars or Moon' },
  { name: 'Go Out to Eat' },
  { name: 'Eat a Favorite Food' },
  { name: 'Cook a Healthy Meal' },
  { name: 'Go on a Picnic' },
  { name: 'Sit in a Peaceful Place' },
  { name: 'Listen to Educational Podcasts or Audio Books' },
  { name: 'Take a Weekend Trip' },
  { name: 'Play a Video Game' },
  { name: 'Surf the Web' },
  { name: 'Garden' },
  { name: 'Go to a Movie' }
])
