EventIdea.create([
  { name: 'Do Yoga' },
  { name: 'Dress Up for Fun' },
  { name: 'Contribute to a Charitable Group' },
  { name: 'Take a Trip to the Countryside' },
  { name: 'Talk About Sports' },
  { name: 'Meet Someone New' },
  { name: 'Go to a Concert' },
  { name: 'Play Baseball or Softball' },
  { name: 'Plan Trips or Vacations' },
  { name: 'Buy Things for Myself' },
  { name: 'Do Artwork (Painting, Sculpture, Drawing, Movie-Making, etc.)' },
  { name: 'Read Sacred Works' },
  { name: 'Play Golf' },
  { name: 'Rearrange or Redecorate My Room or House' },
  { name: 'Go to a Sports Event' },
  { name: 'Read a “Do It Yourself” Article' },
  { name: 'Do a “Do It Yourself” Project' },
  { name: 'Read' },
  { name: 'Go to a Bar, Tavern, Club, etc.' },
  { name: 'Go to Lectures or Hear Speakers' },
  { name: 'Go for a Drive' },
  { name: 'Breathe Clean Air' },
  { name: 'Think Up or Arrange a Song or Music' },
  { name: 'Meditate' },
  { name: 'Please a Friend or Family Member' },
  { name: 'Restore Antiques, Finish Furniture, etc.' },
  { name: 'Watch TV' },
  { name: 'Talk to Myself' },
  { name: 'Camp' },
  { name: 'Work on Machines (Cars, Bikes, Motorcycles, etc.)' },
  { name: 'Think About Something Good in the Future' },
  { name: 'Play Cards' },
  { name: 'Complete a Difficult Task' },
  { name: 'Watch a Comedy Movie or TV Show' },
  { name: 'Solve a Problem, Puzzle, Crossword, etc.' },
  { name: 'Shave' },
  { name: 'Have Lunch with Friends or Associates' },
  { name: 'Play Tennis' },
  { name: 'Take a Shower' },
  { name: 'Drive Long Distances' },
  { name: 'Woodwork or Do Carpentry' },
  { name: 'Write Short Stories, Novels, Plays, or Poetry' },
  { name: 'Be with Animals' },
  { name: 'Explore (Hike Away from Known Routes, etc.)' },
  { name: 'Have a Frank and Open Conversation' },
  { name: 'Sing in a Group' },
  { name: 'Work on My Job' },
  { name: 'Go to a Party' },
  { name: 'Go to Church Functions (Socials, Classes, Bazaars, etc.)' },
  { name: 'Speak a Foreign Language' },
  { name: 'Go to Services, Civic, or Social Club Meetings' },
  { name: 'Go to a Business Meeting or a Convention' },
  { name: 'Play a Musical Instrument' },
  { name: 'Make Snacks' },
  { name: 'Ski' },
  { name: 'Comb or Brush My Hair' },
  { name: 'Act' },
  { name: 'Take a Nap' },
  { name: 'Be with Friends' },
  { name: 'Can, Freeze, or Make Preserves' },
  { name: 'Make Art' },
  { name: 'Solve a Personal Problem' },
  { name: 'Take a Bath' },
  { name: 'Sing to Myself' },
  { name: 'Make Food or Crafts to Sell or Give Away' },
  { name: 'Play Pool or Billiards' },
  { name: 'Be with My Grandchildren' },
  { name: 'Play Chess or Checkers' },
  { name: 'Do Craft Work (Pottery, Jewelry, Leather, Beads, Weaving, etc.)' },
  { name: 'Put on Makeup, Fix My Hair, etc.' },
  { name: 'Design or Draft' },
  { name: 'Visit People Who Are Sick, Shut In, or in Trouble' },
  { name: 'Bowl' },
  { name: 'Be Popular at a Gathering' },
  { name: 'Watch Wild Animals' },
  { name: 'Garden, Landscape, or Do Yard Work' },
  { name: 'Wear New Clothes' },
  { name: 'Dance' },
  { name: 'Sit in the Sun' },
  { name: 'Just Sit and Think' },
  { name: 'Go to a Fair, Carnival, Circus, Zoo, or Amusement Park' },
  { name: 'Talk About Philosophy or Religion' },
  { name: 'Plan or Organize Something' },
  { name: 'Have a Drink by Myself' },
  { name: 'Listen to the Sounds of Nature' },
  { name: 'Go on a Date' },
  { name: 'Have a Lively Talk' },
  { name: 'Listen to the Radio' },
  { name: 'Have Friends Come to Visit' },
  { name: 'Play in a Sporting Competition' },
  { name: 'Introduce People I Think Would Like Each Other' },
  { name: 'Give Gifts' },
  { name: 'Get Massages or Backrubs' },
  { name: 'Watch the Sky, Clouds, or a Storm' },
  { name: 'Improve My Health (Have My Teeth Fixed, Get New Glasses, Begin an Exercise Program, Change My Diet, etc.)' },
  { name: 'Be Downtown' },
  { name: 'Play in a Musical Group' },
  { name: 'Hike' },
  { name: 'Go to a Museum or Exhibit' },
  { name: 'Write Papers, Essays, Articles, Reports, Memos, etc.' },
  { name: 'Do a Job Well' },
  { name: 'Have Spare Time' },
  { name: 'Fish' },
  { name: 'Loan Something' },
  { name: 'Counsel Someone' },
  { name: 'Go to a Health Club, Spa, etc.' },
  { name: 'Learn to Do Something New' },
  { name: 'Go to a “Drive-In”' },
  { name: 'Compliment or Praise Someone' },
  { name: 'Think About People I Like' },
  { name: 'Be with My Parents' },
  { name: 'Ride a Horse' },
  { name: 'Talk on the Telephone' },
  { name: 'Daydream' },
  { name: 'Kick Leaves, Sand, Pebbles, etc.' },
  { name: 'Play Lawn Sports (Badminton, Croquet, Shuffleboard, Horseshoes, etc.)' },
  { name: 'Go to School Reunions, Alumni Meetings, etc.' },
  { name: 'Go to the Movies' },
  { name: 'Kiss My Partner' },
  { name: 'Be Alone' },
  { name: 'Budget My Time' },
  { name: 'Cook Meals' },
  { name: 'Do a Project in My Own Way' },
  { name: 'Do “Odd Jobs” Around the House' },
  { name: 'Cry' },
  { name: 'Be at a Family Reunion or Get-Together' },
  { name: 'Give a Party or Get-Together' },
  { name: 'Wash My Hair' },
  { name: 'Coach Someone' },
  { name: 'Go to a Restaurant' },
  { name: 'Use Cologne, Perfume, or Aftershave' },
  { name: 'Reminisce or Talk About Old Times' },
  { name: 'Get Up Early in the Morning' },
  { name: 'Enjoy Peace and Quiet' },
  { name: 'Do Experiments or Other Scientific Work' },
  { name: 'Visit Friends' },
  { name: 'Write in a Diary' },
  { name: 'Journal' },
  { name: 'Play Football' },
  { name: 'Say Prayers' },
  { name: 'Give Massages or Backrubs' },
  { name: 'Do Favors for People' },
  { name: 'Talk with People on the Job or in Class' },
  { name: 'Be Relaxed' },
  { name: 'Offer Help or Advice' },
  { name: 'Think About Other People’s Problems' },
  { name: 'Play Board Games (Monopoly, Scrabble, etc.)' },
  { name: 'Do Heavy Outdoor Work (Cutting or Chopping Wood, Clearing Land, Farm Work, etc.)' },
  { name: 'Read the Newspaper' },
  { name: 'Play Ping-Pong' },
  { name: 'Brush My Teeth' },
  { name: 'Swim' },
  { name: 'Run, Jog, or Do Gymnastics, Fitness, or Field Exercises' },
  { name: 'Walk Barefoot' },
  { name: 'Play Frisbee or Catch' },
  { name: 'Do Housework or Laundry; Clean Things' },
  { name: 'Be with My Roommate' },
  { name: 'Listen to Music' },
  { name: 'Argue a Point' },
  { name: 'Knit, Crochet, Embroider, or Do Fancy Needlework' },
  { name: 'Go to a Barber or Beautician' },
  { name: 'Have House Guests' },
  { name: 'Be with Someone I Love' },
  { name: 'Read Magazines' },
  { name: 'Sleep In Late' },
  { name: 'Start a New Project' },
  { name: 'Finish a Project' },
  { name: 'Have Sex' },
  { name: 'Explore Sexual Desires' },
  { name: 'Go to the Library' },
  { name: 'Play Soccer, Rugby, Hockey, Lacrosse, etc.' },
  { name: 'Prepare a New or Special Food' },
  { name: 'Watch Birds' },
  { name: 'Shop' },
  { name: 'Watch People' },
  { name: 'Build or Watch a Fire' },
  { name: 'Win an Argument' },
  { name: 'Sell or Trade Something' },
  { name: 'Finish a Project or Task' },
  { name: 'Confess or Apologize' },
  { name: 'Repair Things' },
  { name: 'Work with Others as a Team' },
  { name: 'Bicycle' },
  { name: 'Give Direction to Others' },
  { name: 'Be with Happy People' },
  { name: 'Play Party Games' },
  { name: 'Write Letters, Cards, or Notes' },
  { name: 'Talk About Politics or Public Affairs' },
  { name: 'Ask for Help or Advice' },
  { name: 'Go to Banquets, Luncheons, Potlucks, etc.' },
  { name: 'Talk About My Hobby or Special Interest' },
  { name: 'Smile at People' },
  { name: 'Play in Sand, a Stream, the Grass, etc.' },
  { name: 'Be with My Husband, Wife, or Partner' },
  { name: 'Go on Field Trips, Nature Walks, etc.' },
  { name: 'Express My Love to Someone' },
  { name: 'Care for Houseplants' },
  { name: 'Have Coffee, Tea, etc., with Friends' },
  { name: 'Take a Walk' },
  { name: 'Collect Things' },
  { name: 'Play Handball, Paddleball, Squash, etc.' },
  { name: 'Sew' },
  { name: 'Remember a Departed Friend or Loved One, Visit the Cemetery' },
  { name: 'Do Things with Children' },
  { name: 'Eat Snacks' },
  { name: 'Stay Up Late' },
  { name: 'Be with My Children' },
  { name: 'Go to Auctions, Garage Sales, etc.' },
  { name: 'Think About an Interesting Question' },
  { name: 'Do Volunteer Work, Work on Community Service Projects' },
  { name: 'Defend or Protect Someone; Stop Fraud or Abuse' },
  { name: 'Hear a Good Sermon or Meditation Teaching' },
  { name: 'Compete in a Sport or Game' },
  { name: 'Make a New Friend' },
  { name: 'Talk About My Job or School' },
  { name: 'Read Cartoons, Comic Strips, or Comic Books' },
  { name: 'Borrow Something' },
  { name: 'Travel with a Group' },
  { name: 'See Old Friends' },
  { name: 'Teach Someone' },
  { name: 'Use My Strength' },
  { name: 'Travel' },
  { name: 'Go to Office Parties or Department Get-Togethers' },
  { name: 'Attend a Concert, Opera, or Ballet' },
  { name: 'Play with Pets' },
  { name: 'Go to a Play' },
  { name: 'Look at the Stars or Moon' },
  { name: 'Be Coached' },
  { name: 'Get a Massage' },
  { name: 'Go Out to Eat' },
  { name: 'Eat a Favorite Food' },
  { name: 'Cook a Healthy Meal' },
  { name: 'Go on a Picnic' },
  { name: 'Sit in a Peaceful Place' },
  { name: 'Listen to Educational Tapes, Relaxation Tapes, or Audio Books' },
  { name: 'Take a Long Weekend' },
  { name: 'Play a Video or Computer Game' },
  { name: 'Surf the Internet' },
  { name: 'Garden' },
  { name: 'Plan a Vacation' },
  { name: 'Go to a Movie' },
  { name: 'Watch a Video' }
])
